# Generated by Django 4.2 on 2023-05-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='maximum_discount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_purchase',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
