# Generated by Django 4.2 on 2023-06-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_remove_order_total_price_order_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='total_price',
        ),
    ]
