# Generated by Django 4.2 on 2023-06-21 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_rename_order_total_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='percent',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_purchase',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
