# Generated by Django 4.2 on 2023-06-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_rename_percent_coupon_amount_coupon_minimum_purchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amount',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
