# Generated by Django 4.2 on 2023-06-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
