# Generated by Django 4.2 on 2023-06-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(default='dummy.png', null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='dummy.png', null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='dummy.png', null=True, upload_to='photos/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(default='dummy.png', null=True, upload_to='photos/products'),
        ),
    ]
