# Generated by Django 4.2 on 2023-06-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reason',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
